const STORAPEDIA_API_KEY = '{{ .Env.STORAPEDIA_API_KEY }}';
    const STORAPEDIA_AUTH_DOMAIN = '{{ .Env.STORAPEDIA_AUTH_DOMAIN }}';
    const STORAPEDIA_PROJECT_ID = '{{ .Env.STORAPEDIA_PROJECT_ID }}';
    const STORAPEDIA_STORAGE_BUCKET = '{{ .Env.STORAPEDIA_STORAGE_BUCKET }}';
    const STORAPEDIA_MESSAGING_SENDER_ID = '{{ .Env.STORAPEDIA_MESSAGING_SENDER_ID }}';
    const STORAPEDIA_APP_ID = '{{ .Env.STORAPEDIA_APP_ID }}';
    const STORAPEDIA_DATABASE_URL = '{{ .Env.STORAPEDIA_DATABASE_URL }}';

    const Maps_API_KEY = '{{ .Env.MAPS_API_KEY }}';